<template>
	<div class="bg-gray-100">
		<section class="py-16 2xl:pt-24 2xl:pb-24">
			<div class="container px-4 mx-auto">
				<div class="mb-8 2xl:mb-20 text-center py-10">
					<h2 class="nl-title mb-12 font-heading font-bold text-3xl md:text-5xl leading-none">Frequently Asked Questions</h2>
				</div>
				<div class="flex flex-wrap -mx-4">
					<div class="w-full md:w-1/1 px-4 mb-8">
						<h4 class="mb-2 md:mb-4 text-2xl font-semibold text-green-700">How it works ?</h4>
						<p class="text-sm md:text-base leading-loose text-blueGray-500">
							The user has to buy an NFT on the NoLossClub platform, each NFT is unique, and if your NFT wins in the lucky draw you get the money. If your NFT does not win you can exchange the NFT and get the money that you have deposited. If you do not exchange the NFT you are eligible for the future
							prizes until you withdraw NFT.
						</p>
					</div>
					<div class="w-full md:w-1/3 px-4 mb-8">
						<h4 class="mb-2 md:mb-4 text-2xl font-semibold text-green-700">Do I need to Enter the Club again?</h4>
						<p class="text-sm md:text-base leading-loose text-blueGray-500">No, once you have purchased the NFT you are eligible for all the future prizes until you withdraw with money.</p>
					</div>

					<div class="w-full md:w-1/3  px-4 mb-8">
						<h4 class="mb-2 md:mb-4 text-2xl font-semibold text-green-700">Is there any risk of losing money ?</h4>
						<p class="text-sm md:text-base leading-loose text-blueGray-500">No there is no risk until the protocol operates as intended. Still, you may not add the funds you are not comfortable losing.</p>
					</div>

					<div class="w-full md:w-1/3  px-4 mb-8">
						<h4 class="mb-2 md:mb-4 text-2xl font-semibold text-green-700">Where does the prize money come from?</h4>
						<p class="text-sm md:text-base leading-loose text-blueGray-500">The prize is generated by the interest in the deposited fund, when someone buys the NFT on our platform, the amount is routed to other decentralized finance protocols to start earning interest.</p>
					</div>

				</div>
			</div>
		</section>
	</div>
</template>
