name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.4.0

      - name: Install Yarn
        run: |
          sudo apt-get update -y 
          sudo apt install git -y
          
      - name: Install and Build Project
        run: |
          npm i
          npm run build
          
      - name: Deploy App
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
